/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.
import { Route as rootRouteImport } from './routes/__root';
import { Route as TokenRouteImport } from './routes/token';
import { Route as PaymentRouteImport } from './routes/payment';
import { Route as OrdersRouteImport } from './routes/orders';
import { Route as MenuRouteImport } from './routes/menu';
import { Route as LoginRouteImport } from './routes/login';
import { Route as CartRouteImport } from './routes/cart';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AdminIndexRouteImport } from './routes/admin.index';
import { Route as AdminTablesRouteImport } from './routes/admin.tables';
import { Route as AdminOrdersRouteImport } from './routes/admin.orders';
import { Route as AdminMenuRouteImport } from './routes/admin.menu';
const TokenRoute = TokenRouteImport.update({
    id: '/token',
    path: '/token',
    getParentRoute: () => rootRouteImport,
});
const PaymentRoute = PaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => rootRouteImport,
});
const OrdersRoute = OrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => rootRouteImport,
});
const MenuRoute = MenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => rootRouteImport,
});
const LoginRoute = LoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => rootRouteImport,
});
const CartRoute = CartRouteImport.update({
    id: '/cart',
    path: '/cart',
    getParentRoute: () => rootRouteImport,
});
const AdminRoute = AdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => rootRouteImport,
});
const IndexRoute = IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRouteImport,
});
const AdminIndexRoute = AdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminRoute,
});
const AdminTablesRoute = AdminTablesRouteImport.update({
    id: '/tables',
    path: '/tables',
    getParentRoute: () => AdminRoute,
});
const AdminOrdersRoute = AdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AdminRoute,
});
const AdminMenuRoute = AdminMenuRouteImport.update({
    id: '/menu',
    path: '/menu',
    getParentRoute: () => AdminRoute,
});
const AdminRouteChildren = {
    AdminMenuRoute: AdminMenuRoute,
    AdminOrdersRoute: AdminOrdersRoute,
    AdminTablesRoute: AdminTablesRoute,
    AdminIndexRoute: AdminIndexRoute,
};
const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren);
const rootRouteChildren = {
    IndexRoute: IndexRoute,
    AdminRoute: AdminRouteWithChildren,
    CartRoute: CartRoute,
    LoginRoute: LoginRoute,
    MenuRoute: MenuRoute,
    OrdersRoute: OrdersRoute,
    PaymentRoute: PaymentRoute,
    TokenRoute: TokenRoute,
};
export const routeTree = rootRouteImport
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes();
